name: Publicar no Repositório do QGIS

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar o QGIS-Plugin-CI
        run: pip install qgis-plugin-ci

      - name: Enviar para o Repositório Oficial do QGIS
        # Aqui está a grande diferença: usamos a flag --qgis-token
        run: |
          qgis-plugin-ci release ${{ github.event.release.tag_name }} \
            --qgis-token "${{ secrets.QGIS_PLUGIN_TOKEN }}"